src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $Priority = null;

    #[ORM\Column(length: 255)]
    private ?string $created_by = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->Priority;
    }

    public function setPriority(string $Priority): static
    {
        $this->Priority = $Priority;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('status')
            ->add('date')
            ->add('Priority')
            ->add('created_by')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Entity\User;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class TaskController extends AbstractController
{

    #[Route('/', name: 'app_task_index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SessionInterface $session): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task, SessionInterface $session): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->request->get('_token'))) {
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <h1>Task index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Status</th>
                <th>Date</th>
                <th>Priority</th>
                <th>Created_by</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.name }}</td>
                <td>{{ task.status }}</td>
                <td>{{ task.date ? task.date|date('Y-m-d') : '' }}</td>
                <td>{{ task.Priority }}</td>
                <td>{{ task.createdBy }}</td>
                <td>
<<<<<<< HEAD
                {% if app.user and app.user.email == task.createdBy %}
=======
                {% if app.user.email == task.createdBy %}
>>>>>>> 672b2c6d9e8d024b2a7bc116a83d9b143f112971
                    <a href="{{ path('app_task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>
                {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_task_new') }}">Create new</a>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <h1>Create new Task</h1>

    {{ include('task/_form.html.twig') }}

    <a href="{{ path('app_task_index') }}">back to list</a>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ task.status }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ task.date ? task.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ task.Priority }}</td>
            </tr>
            <tr>
                <th>Created_by</th>
                <td>{{ task.createdBy }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_task_index') }}">back to list</a>

    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}